# BookOasis 독서 지표를 업적 카드 정의로 변환하는 정적 카탈로그입니다.
from __future__ import annotations


DEFINITION_REVISION = 2


ACHIEVEMENT_DEFINITIONS = (
    {
        "key": "reading_started_1",
        "category": "reading",
        "title": "오아시스의 첫 장",
        "description": "BookOasis에서 첫 번째 책을 읽어 보세요.",
        "icon": "fa-solid fa-book-open",
        "metric": "books_started",
        "target": 1,
        "unit": "권",
        "rarity": "common",
    },
    {
        "key": "books_completed_1",
        "category": "completion",
        "title": "첫 번째 완독",
        "description": "책 한 권을 끝까지 읽어 보세요.",
        "icon": "fa-solid fa-circle-check",
        "metric": "books_completed",
        "target": 1,
        "unit": "권",
        "rarity": "common",
    },
    {
        "key": "books_completed_5",
        "category": "completion",
        "title": "책장 채우기",
        "description": "책 5권을 완독해 보세요.",
        "icon": "fa-solid fa-book",
        "metric": "books_completed",
        "target": 5,
        "unit": "권",
        "rarity": "rare",
    },
    {
        "key": "books_completed_10",
        "category": "completion",
        "title": "열 권의 여정",
        "description": "책 10권을 완독해 보세요.",
        "icon": "fa-solid fa-layer-group",
        "metric": "books_completed",
        "target": 10,
        "unit": "권",
        "rarity": "rare",
    },
    {
        "key": "books_completed_25",
        "category": "completion",
        "title": "독서 수집가",
        "description": "책 25권을 완독해 보세요.",
        "icon": "fa-solid fa-book-bookmark",
        "metric": "books_completed",
        "target": 25,
        "unit": "권",
        "rarity": "epic",
    },
    {
        "key": "books_completed_50",
        "category": "completion",
        "title": "오아시스 사서",
        "description": "책 50권을 완독해 보세요.",
        "icon": "fa-solid fa-building-columns",
        "metric": "books_completed",
        "target": 50,
        "unit": "권",
        "rarity": "epic",
    },
    {
        "key": "books_completed_100",
        "category": "completion",
        "title": "백 권의 기록",
        "description": "책 100권을 완독해 보세요.",
        "icon": "fa-solid fa-crown",
        "metric": "books_completed",
        "target": 100,
        "unit": "권",
        "rarity": "legendary",
    },
    {
        "key": "fixed_pages_1000",
        "category": "volume",
        "title": "천 페이지의 발자국",
        "description": "고정 페이지 도서에서 1,000페이지를 읽어 보세요.",
        "icon": "fa-solid fa-file-lines",
        "metric": "fixed_pages_read",
        "target": 1000,
        "unit": "페이지",
        "rarity": "rare",
    },
    {
        "key": "fixed_pages_5000",
        "category": "volume",
        "title": "페이지 항해자",
        "description": "고정 페이지 도서에서 5,000페이지를 읽어 보세요.",
        "icon": "fa-solid fa-compass",
        "metric": "fixed_pages_read",
        "target": 5000,
        "unit": "페이지",
        "rarity": "epic",
    },
    {
        "key": "fixed_pages_10000",
        "category": "volume",
        "title": "만 페이지의 바다",
        "description": "고정 페이지 도서에서 10,000페이지를 읽어 보세요.",
        "icon": "fa-solid fa-water",
        "metric": "fixed_pages_read",
        "target": 10000,
        "unit": "페이지",
        "rarity": "legendary",
    },
    {
        "key": "streak_3",
        "category": "streak",
        "title": "삼일의 리듬",
        "description": "3일 연속으로 책을 읽어 보세요.",
        "icon": "fa-solid fa-fire-flame-curved",
        "metric": "longest_streak",
        "target": 3,
        "unit": "일",
        "rarity": "common",
    },
    {
        "key": "streak_7",
        "category": "streak",
        "title": "일주일의 습관",
        "description": "7일 연속으로 책을 읽어 보세요.",
        "icon": "fa-solid fa-calendar-week",
        "metric": "longest_streak",
        "target": 7,
        "unit": "일",
        "rarity": "rare",
    },
    {
        "key": "streak_14",
        "category": "streak",
        "title": "두 주의 몰입",
        "description": "14일 연속으로 책을 읽어 보세요.",
        "icon": "fa-solid fa-bolt",
        "metric": "longest_streak",
        "target": 14,
        "unit": "일",
        "rarity": "epic",
    },
    {
        "key": "streak_30",
        "category": "streak",
        "title": "한 달의 독서가",
        "description": "30일 연속으로 책을 읽어 보세요.",
        "icon": "fa-solid fa-medal",
        "metric": "longest_streak",
        "target": 30,
        "unit": "일",
        "rarity": "legendary",
    },
    {
        "key": "genres_3",
        "category": "explorer",
        "title": "장르 산책",
        "description": "서로 다른 장르 3개를 완독해 보세요.",
        "icon": "fa-solid fa-signs-post",
        "metric": "distinct_genres",
        "target": 3,
        "unit": "장르",
        "rarity": "common",
    },
    {
        "key": "genres_5",
        "category": "explorer",
        "title": "장르 탐험가",
        "description": "서로 다른 장르 5개를 완독해 보세요.",
        "icon": "fa-solid fa-map",
        "metric": "distinct_genres",
        "target": 5,
        "unit": "장르",
        "rarity": "rare",
    },
    {
        "key": "tags_10",
        "category": "explorer",
        "title": "취향의 지도",
        "description": "완독한 책에서 서로 다른 태그 10개를 만나 보세요.",
        "icon": "fa-solid fa-tags",
        "metric": "distinct_tags",
        "target": 10,
        "unit": "태그",
        "rarity": "epic",
    },
    {
        "key": "audio_started_1",
        "category": "audio",
        "title": "첫 번째 목소리",
        "description": "첫 오디오북을 재생해 보세요.",
        "icon": "fa-solid fa-headphones",
        "metric": "audiobooks_started",
        "target": 1,
        "unit": "권",
        "rarity": "common",
    },
    {
        "key": "audio_completed_1",
        "category": "audio",
        "title": "첫 번째 완청",
        "description": "오디오북 한 권을 끝까지 들어 보세요.",
        "icon": "fa-solid fa-volume-high",
        "metric": "audiobooks_completed",
        "target": 1,
        "unit": "권",
        "rarity": "common",
    },
    {
        "key": "audio_completed_5",
        "category": "audio",
        "title": "귀로 읽는 서재",
        "description": "오디오북 5권을 완청해 보세요.",
        "icon": "fa-solid fa-podcast",
        "metric": "audiobooks_completed",
        "target": 5,
        "unit": "권",
        "rarity": "rare",
    },
    {
        "key": "audio_completed_10",
        "category": "audio",
        "title": "오디오 애호가",
        "description": "오디오북 10권을 완청해 보세요.",
        "icon": "fa-solid fa-radio",
        "metric": "audiobooks_completed",
        "target": 10,
        "unit": "권",
        "rarity": "epic",
    },
    {
        "key": "audio_completed_25",
        "category": "audio",
        "title": "목소리의 기록관",
        "description": "오디오북 25권을 완청해 보세요.",
        "icon": "fa-solid fa-microphone-lines",
        "metric": "audiobooks_completed",
        "target": 25,
        "unit": "권",
        "rarity": "legendary",
    },
    {
        "key": "video_started_1",
        "category": "video",
        "title": "첫 번째 상영",
        "description": "첫 비디오를 시청해 보세요.",
        "icon": "fa-solid fa-circle-play",
        "metric": "videos_started",
        "target": 1,
        "unit": "편",
        "rarity": "common",
    },
    {
        "key": "video_completed_1",
        "category": "video",
        "title": "엔딩 크레딧",
        "description": "비디오 한 편을 끝까지 시청해 보세요.",
        "icon": "fa-solid fa-clapperboard",
        "metric": "videos_completed",
        "target": 1,
        "unit": "편",
        "rarity": "common",
    },
    {
        "key": "video_completed_5",
        "category": "video",
        "title": "주말 상영관",
        "description": "비디오 5편을 완주해 보세요.",
        "icon": "fa-solid fa-film",
        "metric": "videos_completed",
        "target": 5,
        "unit": "편",
        "rarity": "rare",
    },
    {
        "key": "video_completed_10",
        "category": "video",
        "title": "정주행의 시작",
        "description": "비디오 10편을 완주해 보세요.",
        "icon": "fa-solid fa-forward-fast",
        "metric": "videos_completed",
        "target": 10,
        "unit": "편",
        "rarity": "epic",
    },
    {
        "key": "video_completed_25",
        "category": "video",
        "title": "오아시스 시네마테크",
        "description": "비디오 25편을 완주해 보세요.",
        "icon": "fa-solid fa-award",
        "metric": "videos_completed",
        "target": 25,
        "unit": "편",
        "rarity": "legendary",
    },
)


CATEGORY_DEFINITIONS = (
    {"key": "reading", "title": "첫걸음", "icon": "fa-solid fa-book-open-reader"},
    {"key": "completion", "title": "완독", "icon": "fa-solid fa-trophy"},
    {"key": "volume", "title": "독서량", "icon": "fa-solid fa-file-circle-check"},
    {"key": "streak", "title": "연속 독서", "icon": "fa-solid fa-fire"},
    {"key": "explorer", "title": "탐험", "icon": "fa-solid fa-route"},
    {"key": "audio", "title": "오디오북", "icon": "fa-solid fa-headphones-simple"},
    {"key": "video", "title": "비디오북", "icon": "fa-solid fa-film"},
)
